#######################################
#      CXX Driver Config for MCI      #
#######################################

#######################################
#            Functions                #
#######################################

functions:
    "fetch_source":
        command: git.get_project
        params:
            directory: "mongo-cxx-driver"

    "install_c_driver":
        command: shell.exec
        params:
            working_dir: "."
            script: |
                git clone https://github.com/mongo/mongo-c-driver.git
                cd mongo-c-driver
                ./autogen.sh --prefix="$(pwd)/c-driver-install" --enable-tests=no --enable-examples=no
                make
                make install

#######################################
#              Pre Task               #
#######################################

pre:
  - command: expansions.fetch
    params:
      keys:
        - local_key: "aws_key"
          remote_key: "project_aws_key"
        - local_key: "aws_secret"
          remote_key: "project_aws_secret"
  - command: shell.exec
    params:
      script: |
        rm -rf "mongo-cxx-driver"
        rm -fr "mongo-c-driver"
        rm -fr "c-driver-install"

#######################################
#               Tasks                 #
#######################################

tasks:
    - name: compile_and_test
      commands:
        - func: "fetch_source"
        - command: git.apply_patch
          params:
              directory: "mongo-cxx-driver"
        - command: shell.exec
          params:
              working_dir: "mongo-cxx-driver/build"
              script: |
                  PKG_CONFIG_PATH="../c-driver-install -DBUILD_UNIT_TESTS=on -DCMAKE_BUILD_TYPE=${build_type} ..
                  make
                  make test

#######################################
#           Buildvariants             #
#######################################

buildvariants:

    #######################################
    #         Linux Buildvariants         #
    #######################################
    - name: ubuntu1404-release
      display_name: "Ubuntu 14.04 LTS (Trusty Tahr) Release"
      expansions:
          build_type: "Release"
      run_on:
          - ubuntu1404-test
      tasks:
          - compile_and_test

    - name: ubuntu1404-debug
      display_name: "Ubuntu 14.04 LTS (Trusty Tahr) Debug"
      expansions:
          build_type: "Debug"
      run_on:
          - ubuntu1404-test
      tasks:
          - compile_and_test
