language: cpp
env:
  global:
    - PREFIX=$(mktemp -d /tmp/mongo-cxx-driver-install.XXXXXX || exit 1)

script:
    - $CXX --version
    - scons
       -j2
       --mute
       --prefix=$PREFIX
       --use-system-boost
       --full
       --sharedclient
       --ssl
       --use-sasl-client
       --dbg=on
       test
       clientTests
       check-install-mongoclient
compiler:
    - gcc

# Setup repos etc before installation
before_install:
    - sudo add-apt-repository -y ppa:boost-latest/ppa
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libboost1.55-all-dev
